### ISSUE TITLE
What does this do and why does it exist?

### ISSUE THREAD

**Issue by gunnihinn** [lomik/zapwriter#2]
$subject.

The answers to these questions is not very clear from the readme or the git history.

**Comment by lomik** [comment]
PRs with readme are welcome ;)

**Comment by gunnihinn** [comment]
lol :D 

I don't mind writing things, but I really don't know the answer to the questions I asked. If you can say a little about that, I can try to summarize it and make a PR to the readme.

**Comment by lomik** [comment]
This is just reusable helper for my own public and private projects. I have no purpose and no desire to document and sell it.

Perhaps something similar is already part of the zap. I have not checked for a long time

**Comment by gunnihinn** [comment]
That's fine. Maybe I can phrase my question differently. What was missing from zap that made you write this? I can see _what_ this thing is doing, but I can only guess at _why_ it's doing it.

**Comment by lomik** [comment]
Primary goals was:
1.  File output with rotation support 
2. Custom encoder ("mixed"). At the time, it was necessary to maintain backward compatibility in the private projects
3. A flexible output manager who could solve the following problems:
* Write full log to file with level "info" and to stderr with level "error"
* Ability to record a part of the logs into a separate file. Sample, access log of http server. And also to solve feature requests like this https://github.com/lomik/go-carbon/issues/154

Zap could not do any of the above at the time of writing this library

**Comment by gunnihinn** [comment]
Thanks for taking the time to explain this to me.
